---
- name: ensure samba package is installed
  yum: 
    name="samba"
    state="present"
  sudo: yes
  sudo_user: root

- name: samba config
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf owner=root group=root mode=0644
  notify:
    - restart smb
